name: Publish to PyPI
on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: get up on this
        uses: actions/checkout@v4

      - name: hit it
        run: |
          python3 -m venv venv
          . ./venv/bin/activate
          pip install -U .[dev]
          flit publish
